# Generated by Django 5.2.3 on 2025-06-26 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255, unique=True)),
                ('is_grup', models.BooleanField(default=False)),
                ('katilimcilar', models.ManyToManyField(related_name='sohbet_odalari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_mesajlar', to=settings.AUTH_USER_MODEL)),
                ('okundu_bilgisi', models.ManyToManyField(blank=True, related_name='okunan_mesajlar', to=settings.AUTH_USER_MODEL)),
                ('oda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='chat.oda')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
