# Generated by Django 5.2.3 on 2025-06-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_is_read_message_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_by',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
