# Generated by Django 5.2.3 on 2025-06-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_fcmdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCMDevice',
        ),
    ]
