# Generated by Django 5.2.3 on 2025-06-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_devicetoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceToken',
        ),
    ]
