# Generated by Django 5.2.3 on 2025-06-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
